services:
  web:
    image: web
    container_name: web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8443:443"                         # ajout essentiel      
    networks:
      - transcendence
    restart: unless-stopped
networks:
    transcendence:
      driver: bridge
